### ISSUE TITLE
Help! Cannot create new reference vcf file? 

### ISSUE THREAD

**Issue by busrasevimm** [AlgoLab/MALVIRUS#20]
Hello,

I'm trying to create new reference vcf file for GISAID sequences of COVID19. But MALVIRUS failed every time for these sequences. I've 24,497 sequences. And I take these error message from log.json;

{"alias":"20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af","description":"europe","filename":"/jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/europe_2020_07_20_19-2.fasta","gtf":"/jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/sars-cov-2.gff","id":"20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af","log":{"last_time":"2020-08-13 11:11:18","status":"Failed","steps":{"mafft":{"command":"mafft --thread 4 --auto --keeplength --addfragments /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/europe_2020_07_20_19-2.fasta /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/reference.fasta > /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/multi_alignment.unfilled.msa 2> /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/mafft.log","config":{"cores":4,"gtf":"/jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/sars-cov-2.gff","multifa":"/jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/europe_2020_07_20_19-2.fasta","reference":"/jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/reference.fasta","workdir":"/jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af"},"input":{"fa":"/jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/reference.fasta","mfa":"/jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/europe_2020_07_20_19-2.fasta"},"log":"/opt/conda/envs/malva-env/bin/mafft: line 2745:   897 Killed                  \"$prefix/addsingle\" -Q 100 $legacygapopt -W $tuplesize -O $outnum $addsinglearg $addarg $add2ndhalfarg -C $numthreads $memopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f \"-\"$gop -h $aof $param_fft $localparam $algopt $treealg $scoreoutarg < infile > /dev/null 2>> \"$progressfile\"\n","output":{"msa":"/jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/multi_alignment.unfilled.msa"},"params":{},"result":"Failed","return_code":1,"time":"2020-08-13 11:11:18"}}},"params":{"cores":"4"},"reference":"/jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/reference.fasta","snakemake":"Building DAG of jobs...\nUsing shell: /bin/bash\nProvided cores: 4\nRules claiming more threads will be scaled down.\nJob counts:\n\tcount\tjobs\n\t1\tfill_msa\n\t1\tindex_reference\n\t1\tmulti_align\n\t1\trun\n\t1\tvcf_add_freqs\n\t1\tvcf_build\n\t1\tvcf_clean_header\n\t7\n\n[Thu Aug 13 11:10:42 2020]\nrule multi_align:\n    input: /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/reference.fasta, /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/europe_2020_07_20_19-2.fasta\n    output: /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/multi_alignment.unfilled.msa\n    log: /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/mafft.log, /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/mafft.json\n    jobid: 6\n    threads: 4\n\n\u001b[33mJob counts:\n\tcount\tjobs\n\t1\tmulti_align\n\t1\u001b[0m\n\u001b[32m[Thu Aug 13 11:11:18 2020]\u001b[0m\n\u001b[31mError in rule multi_align:\u001b[0m\n\u001b[31m    jobid: 0\u001b[0m\n\u001b[31m    output: /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/multi_alignment.unfilled.msa\u001b[0m\n\u001b[31m    log: /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/mafft.log, /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/mafft.json (check log file(s) for error message)\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mRuleException:\nCalledProcessError in line 102 of /snakemake/Snakefile.vcf:\nCommand 'mafft --thread 4 --auto --keeplength --addfragments /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/europe_2020_07_20_19-2.fasta /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/reference.fasta > /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/multi_alignment.unfilled.msa 2> /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/mafft.log' returned non-zero exit status 1.\n  File \"/snakemake/Snakefile.vcf\", line 112, in __rule_multi_align\n  File \"/snakemake/Snakefile.vcf\", line 102, in __rule_multi_align\n  File \"/opt/conda/envs/malva-env/lib/python3.7/subprocess.py\", line 411, in check_output\n  File \"/opt/conda/envs/malva-env/lib/python3.7/subprocess.py\", line 512, in run\n  File \"/opt/conda/envs/malva-env/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\u001b[0m\n\u001b[31mExiting because a job execution failed. Look above for error message\u001b[0m\nShutting down, this might take some time.\nExiting because a job execution failed. Look above for error message\nComplete log: /jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/.snakemake/log/2020-08-13T111041.968450.snakemake.log\n","submission_time":1597317041}

I'm new this area and I'm trying to understand. Can anybody help me about this error message?

Thanks

**Comment by yp** [comment]
Thanks for reporting the issue.
Could you please attach the file http://localhost:56733/jobs/vcf/20200813-111040_3c253ebf-57bc-4783-95f1-d861b32e84af/mafft/mafft.log ?

**Comment by busrasevimm** [comment]
Here is the file; 

[mafft.log](https://github.com/AlgoLab/MALVIRUS/files/5069280/mafft.log)

**Comment by ldenti** [comment]
Thanks! Unfortunately the log is not very informative 😓

Can you please try to run malvirus on a subset of your input (~10 sequences)?

How much RAM does your system have?

**Comment by busrasevimm** [comment]
I ran the system with 10 sequences. The system is creating the VCF file without any fail. 
I was able to create a reference vcf 3 times before. My previous inputs have ~ 5000 sequences. But in a population with too many sequence numbers, I guess I get this error. 

My system has 16 GB RAM.

Thanks again..

**Comment by ldenti** [comment]
I ran mafft with 25k sequences and it required ~7GB of RAM.

Can you please keep MALVIRUS docker container up and run the following commands:
```
sudo docker ps
```
to get the `CONTAINER ID` of MALVIRUS and then
```
sudo docker stats <CONTAINER_ID>

**Comment by busrasevimm** [comment]
I am using macOS. I did the operations you said. I saw that memory usage was limited to 4 GB and I increased it. I started the vcf creation process. The process was completed successfully without any problems. I think the problem is solved 👍

Thank you very much for your attention and time.

**Comment by yp** [comment]
Closing since the issue seems resolved.
